### ISSUE TITLE
Level Shifting MOSFET and Power Regulator

### ISSUE THREAD

**Issue by iharshadec** [sparkfun/SparkFun_Qwiic_9DoF_IMU_Breakout#3]
Looks Like my board is damaged as it's not generating Power.
What is the regulator and mosfet used in this design?

**Comment by PaulZC** [comment]
Hi @iharshadec ,
Apologies for the delay. From the Eagle files: the regulator is a SP6214-1.8V; the FET is RE1C002UN.
Best wishes,
Paul

**Comment by iharshadec** [comment]
> Hi @iharshadec ,
> Apologies for the delay. From the Eagle files: the regulator is a SP6214-1.8V; the FET is RE1C002UN.
> Best wishes,
> Paul

Thank you Paul,
I will order this regulator first and replace to see if I get the board working back.
