### ISSUE TITLE
How to get this sensor working on lineage OS?

### ISSUE THREAD

**Issue by anivader1789** [sparkfun/SparkFun_Qwiic_9DoF_IMU_Breakout#5]
We have this IMU sensor and we have a rasberry pi 4 Model B. Installed Lineage OS on it (https://konstakang.com/devices/rpi4/LineageOS20/). We want to install drivers for this sensor to work with our setup. Any help appreciated.

**Comment by PaulZC** [comment]
Hi @anivader1789 ,

Please see: https://github.com/sparkfun/Qwiic_9DoF_IMU_ICM20948_Py

Best wishes,
Paul
